# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-18 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='tought',
            new_name='thought',
        ),
    ]
