# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_auto_20191119_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='liked_items',
            new_name='users_that_like',
        ),
    ]
