# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewApp', '0002_auto_20191115_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ManyToManyField(related_name='reviews', to='beltReviewApp.User'),
        ),
    ]
