# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0003_auto_20191122_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='course_commented',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coursesApp.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
    ]
