# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-08 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojos',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
