# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_ninjas', '0003_ninja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojos',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='d_ninjas.Dojo'),
            preserve_default=False,
        ),
    ]
