# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-14 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_auto_20191114_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_pw',
        ),
    ]
