# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_auto_20191119_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wish_list',
            new_name='liked_items',
        ),
    ]
