# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='book description is currently N/A'),
            preserve_default=False,
        ),
    ]
